from pipeline.m0 import CANDIDATE_SPECS, FAMILIES

LABELS = {"equity_awards": "Employee equity awards", "termination_fee": "Termination (break-up) fee",
          "contingent_consideration": "Earn-out or other contingent consideration"}
CANDIDATE_LABELS = {"employee_benefits": "Employees' pay and benefits after the deal (adopted)",
                    "financing": "Buyer financing", "go_shop": "Go-shop period"}


def _ok(v) -> str:
    return "Met" if v else "Not met"


def _families(f) -> str:
    return "\n".join(
        f"| {LABELS[fam]} | {f[f'm0_sample_{fam}_present']} | {f[f'm0_sample_{fam}_share']} "
        f"| {f[f'm0_sample_{fam}_regex']} | {f[f'm0_sample_{fam}_truncated']} |" for fam in FAMILIES)


def _replacement(f) -> str:
    if "m0_candidate_sample" not in f:
        return ""
    rows = "\n".join(
        f"| {CANDIDATE_LABELS[sp.name]} | {f[f'm0_candidate_{sp.name}_present']} | {f[f'm0_candidate_{sp.name}_share']} "
        f"| {f[f'm0_candidate_{sp.name}_regex']} | {f[f'm0_candidate_{sp.name}_truncated']} |" for sp in CANDIDATE_SPECS)
    verdict = "PASS" if f["m0_gate_pass_adopted"] else "FAIL"
    return f"""## Replacement lead family (decided {f['m0_adopted_on']})

The original gate failed on earn-outs, which were not found in the sampled agreements. The PRD records the decision to replace them as a lead family with employees' pay and benefits after the deal; earn-out questions stay as abstention items.

Candidates were measured on the same sample of {f['m0_candidate_sample']} agreements (machine-built). Presence is judged by a model and counts only when its supporting quote occurs verbatim in the passages it was shown. Financing counts include bare buyer termination-fee quotes, so that row reads wider than the financing documents alone.

| Candidate | Present | Share | Pattern matched | Passages cut to fit the prompt |
|---|---|---|---|---|
{rows}

Gate with the adopted family: {verdict}. This is the original gate re-evaluated with the adopted family in place of earn-outs; the original verdict above stays on record.

"""


def _access(f) -> str:
    if "m0_sec_requests" not in f:
        return "No sec.gov request log was found, so the access record is not reported here."
    gap = f["m0_min_request_gap_s"]
    spacing = ("the smallest gap between request starts was " + f"{gap} seconds" if gap is not None
               else "there were too few requests to measure a gap between request starts")
    return (f"Requests made to sec.gov and answered: {f['m0_sec_requests']}; {spacing}; "
            f"refusals met: {f['m0_blocked_events']}; "
            f"server errors met (retried up to twice after a wait): {f['m0_server_errors']}, "
            f"of which recorded after the fact: {f['m0_server_errors_recorded_later']}.")


def render_m0(f) -> str:
    verdict = "PASS" if f["m0_gate_pass"] else "FAIL"
    estimate = (f"Estimated index size from M2's bytes per passage: {f['m0_estimate_index_bytes']} bytes."
                if "m0_estimate_index_bytes" in f else "No index-size estimate: M2's index measurements are not in the facts.")
    return f"""# M0 report: the EDGAR gate

Generated by `dtd report` from `facts.json`. Do not edit by hand. This is not legal advice.

## Gate: {verdict}

- Tech agreements: {f['m0_tech_deals']}, with {f['m0_tech_targets']} distinct target companies; the gate needs at least {f['m0_gate_agreements_min']} agreements. {_ok(f['m0_gate_count_ok'])}.
- Each lead family in at least {f['m0_gate_family_share_min']} of a sample of {f['m0_sample']} tech agreements (the sample aims for {f['m0_sample_target']}) (machine-built). {_ok(f['m0_gate_families_ok'])}.

The verdict rests in part on a machine-built sample: whether each lead family is present was judged by a model, not by a person, so the family condition is an estimate.

If the gate failed, PRD §10's fallback applies before M3 is planned: index the tech deals that exist, lead the demo with the most recognisable, and describe the corpus as public acquisition agreements without the startup framing.

## Lead families in the sample (machine-built)

Presence is judged by `{f['m0_lead_model']}` on passages a broad pattern picked out, and counts only when its supporting quote occurs verbatim in those passages. The pattern's own count is beside it. A family can be judged absent only from the passages the model was shown, so where passages were cut to fit the prompt, an absent verdict is weaker.

| Family | Present | Share | Pattern matched | Passages cut to fit the prompt |
|---|---|---|---|---|
{_families(f)}

{_replacement(f)}## How the corpus was found

Selection rule (PRD §2.2): an EX-2.1 exhibit to an 8-K whose text is an agreement and plan of merger, signed on or after {f['m0_start']}, whose target is an EDGAR registrant with SIC in {f['m0_sic_ranges']}. {_access(f)}

| Step | Count |
|---|---|
| Documents found by full-text search for "agreement and plan of merger" in 8-K filings | {f['m0_search_docs']} |
| Of those, EX-2.1 exhibits | {f['m0_ex21_docs']} |
| Exhibits typed EX-2 without a sub-number (not counted; the selection rule is EX-2.1) | {f['m0_ex2_bare_docs']} |
| Filed by a company with a tech SIC (candidates) | {f['m0_candidates']} |
| Fetched (the rest were missing) | {f['m0_fetched']} ({f['m0_missing']} missing) |
| Fetch errors (counted, not used) | {f['m0_fetch_errors']} |
| Not an agreement and plan of merger by its opening text (excluded) | {f['m0_not_merger']} |
| Fetched documents with a parsed deal identity | {f['m0_keyed']} |
| Preamble names a "Company" | {f['m0_company_parsed']} (rate {f['m0_company_parsed_rate']}) |
| Amendments among them | {f['m0_amendment_docs']} |
| Distinct deals (target, acquirer, signing date) | {f['m0_deals']} (of which {f['m0_orphan_restated']} are known only through an amended and restated agreement) |
| Deals whose target resolved to a filer | {f['m0_deals_resolved']} (rate {f['m0_target_resolved_rate']}) |
| Tech agreements: resolved target with a tech SIC, signed in range | {f['m0_tech_deals']} |
| Distinct target companies among the tech agreements | {f['m0_tech_targets']} |

The target is resolved only against the filing's own filers, on the assumption that a target which is a registrant files its own copy. Tech deals seen in more than one copy: {f['m0_tech_multi_copy']} (rate {f['m0_duplicate_rate']}). Tech deals with an amendment: {f['m0_tech_amended']} (rate {f['m0_amendment_rate']}).

## The fee in the press release (PRD §5.2 cross-check)

Of the sampled deals, {f['m0_press_fee']} state a fee amount in the agreement and {f['m0_press_release']} have an EX-99 exhibit (usually the press release); of the {f['m0_press_both']} with both, {f['m0_press_restated']} restate the amount (share {f['m0_press_restated_share']}). {f['m0_press_unusable']} releases were unusable (for example a PDF with no extractable text) and are not counted as restating. M4 includes the cross-check only if this share is usable.

## Size for M3

Passages in the tech agreements, cut by the same section-aware segmenter as MAUD: {f['m0_passages_total']} in all, {f['m0_passages_mean']} per agreement on average, median {f['m0_passages_median']}. {estimate}
"""
