def render(f: dict) -> str:
    return f"""# M1 report: BM25 baseline on MAUD

Generated by `dtd report` from `facts.json`. Do not edit by hand.

## Corpus

| Fact | Value |
|---|---|
| Agreements | {f['maud_contracts']} |
| Characters | {f['maud_chars']} |
| Passages | {f['maud_passages']} |
| Passages indexed (table-of-contents chunks excluded) | {f['maud_passages_indexed']} |
| Share of indexed passages carrying a section id | {f['maud_passages_with_section_share']} |
| Defined terms found | {f['maud_terms']} |

## Eval set: human-labelled (MAUD)

| Fact | Value |
|---|---|
| Label rows (`main`) | {f['maud_label_rows_main']} |
| Eval items (agreement x deal point) | {f['eval_items']} |
| Items scored | {f['eval_items_scored']} |
| Items dropped: no excerpt piece could be aligned | {f['eval_items_no_gold']} |
| Items dropped: agreement file missing | {f['eval_items_missing_contract']} |
| Excerpt pieces | {f['align_pieces']} |
| Share of pieces aligned to a character span | {f['align_piece_rate']} |

## Rung R1: BM25, retrieval within the agreement

Queries are MAUD's deal-point and question names, verbatim. Headline numbers are on the report
split ({f['r1_report_contracts']} agreements, {f['r1_report_items']} items); the tune split is
held back for choosing settings in later rungs. Intervals are 95%, bootstrapped over agreements.

| Metric | Report split | All agreements |
|---|---|---|
| recall@1 | {f['r1_report_recall_at_1']} | {f['r1_recall_at_1']} |
| recall@5 | {f['r1_report_recall_at_5']} ({f['r1_report_recall_at_5_lo']} to {f['r1_report_recall_at_5_hi']}) | {f['r1_recall_at_5']} |
| recall@10 | {f['r1_report_recall_at_10']} | {f['r1_recall_at_10']} |
| MRR@10 | {f['r1_report_mrr_at_10']} | {f['r1_mrr_at_10']} |
| nDCG@10 | {f['r1_report_ndcg_at_10']} | {f['r1_ndcg_at_10']} |

Latency per query: p50 {f['r1_latency_ms_p50']} ms, p95 {f['r1_latency_ms_p95']} ms.
"""
