from facts.queries import CATEGORIES

# A stratum bootstrapped over fewer agreements than this gets a warning beside its interval.
MIN_CLUSTERS = 10


def _interval(f: dict, name: str) -> str:
    return f"{f[name]} ({f[name + '_lo']} to {f[name + '_hi']})"


def _category_rows(f: dict) -> str:
    rows = []
    for slug, category in CATEGORIES.items():
        p = f"r1_cat_{slug}"
        if f[f"{p}_recall_at_5"] is None:
            rows.append(f"| {category} | no scored items | {f[p + '_items']} | {f[p + '_contracts']} | |")
            continue
        note = "few agreements, interval unreliable" if f[f"{p}_contracts"] < MIN_CLUSTERS else ""
        rows.append(f"| {category} | {_interval(f, p + '_recall_at_5')} | {f[p + '_items']} "
                    f"| {f[p + '_contracts']} | {note} |")
    return "\n".join(rows)


def render(f: dict) -> str:
    return f"""# M1 report: BM25 baseline on MAUD

Generated by `dtd report` from `facts.json`. Do not edit by hand.

## Corpus

| Fact | Value |
|---|---|
| Agreements | {f['maud_contracts']} |
| Characters | {f['maud_chars']} |
| Passages | {f['maud_passages']} |
| Passages indexed (table-of-contents chunks excluded) | {f['maud_passages_indexed']} |
| Share of indexed passages carrying a section id | {f['maud_passages_with_section_share']} |
| Defined terms (distinct per agreement; "means" or parenthetical definitions) | {f['maud_terms_defined']} |
| Cross-references to a definition elsewhere ("has the meaning") | {f['maud_terms_xref']} |

## MAUD labels, recounted

Counted from the three label CSVs, every data type.

| Fact | Value |
|---|---|
| Label rows | {f['maud_label_rows_all']} |
| Agreements named in the labels | {f['maud_label_contracts']} |
| Of those, agreements with a text file | {f['maud_label_contracts_with_text']} |
| Question types | {f['maud_question_types']} |

## Eval set: human-labelled (MAUD)

| Fact | Value |
|---|---|
| Label rows (`main`) | {f['maud_label_rows_main']} |
| Eval items (agreement x deal point) | {f['eval_items']} |
| Items scored | {f['eval_items_scored']} |
| Items dropped: no excerpt piece could be aligned | {f['eval_items_no_gold']} |
| Items dropped: agreement file missing | {f['eval_items_missing_contract']} |
| Excerpt pieces | {f['align_pieces']} |
| Share of pieces aligned to a character span | {f['align_piece_rate']} |
| Pieces too short to align, left out | {f['align_pieces_short']} |
| Aligned pieces that fit more than one place | {f['align_pieces_ambiguous']} |
| Pieces moved off the table of contents to the body | {f['align_pieces_toc_rescued']} |
| Pieces found only in the table of contents (unaligned) | {f['align_pieces_toc_only']} |

## Rung R1: BM25, retrieval within the agreement

Queries are MAUD's deal-point and question names, less their "Answer" suffixes. Headline
numbers are on the report split ({f['r1_report_contracts']} agreements, {f['r1_report_items']} items);
the tune split is held back for choosing settings in later rungs. Intervals are 95%,
bootstrapped over agreements.

| Metric | Report split | All agreements |
|---|---|---|
| recall@1 | {_interval(f, 'r1_report_recall_at_1')} | {f['r1_recall_at_1']} |
| recall@5 | {_interval(f, 'r1_report_recall_at_5')} | {f['r1_recall_at_5']} |
| recall@10 | {_interval(f, 'r1_report_recall_at_10')} | {f['r1_recall_at_10']} |
| MRR@10 | {_interval(f, 'r1_report_mrr_at_10')} | {f['r1_mrr_at_10']} |
| nDCG@10 | {_interval(f, 'r1_report_ndcg_at_10')} | {f['r1_ndcg_at_10']} |

Latency per query: p50 {f['r1_latency_ms_p50']} ms, p95 {f['r1_latency_ms_p95']} ms.

### Per deal-point category (recall@5, all agreements)

| Category | recall@5 | Items | Agreements | Note |
|---|---|---|---|---|
{_category_rows(f)}
"""
